spring:
  datasource:
    url: jdbc:h2:mem:mydb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
        enabled: true
        path: /h2-console
        settings:
            trace: false
            web-allow-others: false
springdoc:
  packagesToScan: au.id.wattle.chapman.strangler.demoMonolith
