openapi: 3.0.1
info:
  title: Demo Monolith API
  description: Demo Monolith ample application
  license:
    name: Apache 2.0
    url: http://springdoc.org
  version: v0.0.1
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /countries/:
    get:
      tags:
        - countries
      operationId: getCountries
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      tags:
        - countries
      operationId: saveCountry
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
        required: true
      responses:
        '200':
          description: OK
  /countries/{code}:
    get:
      tags:
        - countries
      operationId: getCountry
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Country'
components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        code:
          type: string
